name:                 monkeyLang
version:              0.1.0.0
visibility:           public
id:                   monkeyLang-0.1.0.0-inplace
key:                  monkeyLang-0.1.0.0-inplace
license:              MIT
maintainer:           137726307+DNF32@users.noreply.github.com
author:               DNF32
category:             Language
abi:                  inplace
exposed:              True
exposed-modules:      MyLib Token
import-dirs:
    /Users/dnf/scratch/monkeyLang/dist-newstyle/build/aarch64-osx/ghc-9.6.7/monkeyLang-0.1.0.0/build

library-dirs:
    /Users/dnf/scratch/monkeyLang/dist-newstyle/build/aarch64-osx/ghc-9.6.7/monkeyLang-0.1.0.0/build

library-dirs-static:
    /Users/dnf/scratch/monkeyLang/dist-newstyle/build/aarch64-osx/ghc-9.6.7/monkeyLang-0.1.0.0/build

dynamic-library-dirs:
    /Users/dnf/scratch/monkeyLang/dist-newstyle/build/aarch64-osx/ghc-9.6.7/monkeyLang-0.1.0.0/build

data-dir:             /Users/dnf/scratch/monkeyLang/.
hs-libraries:         HSmonkeyLang-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/dnf/scratch/monkeyLang/dist-newstyle/build/aarch64-osx/ghc-9.6.7/monkeyLang-0.1.0.0/doc/html/monkeyLang/monkeyLang.haddock

haddock-html:
    /Users/dnf/scratch/monkeyLang/dist-newstyle/build/aarch64-osx/ghc-9.6.7/monkeyLang-0.1.0.0/doc/html/monkeyLang
